
development: &default
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  s3_region: <%= ENV['S3_REGION'] %>

test:
  access_key_id: 'iamfake'
  secret_access_key: 'iamfake'
  s3_bucket_name: 'iamfake'
  s3_region: 'iamfake'

production:
  <<: *default